version: '3'

services:
  app:
    build: .
    ports:
      - "8888:8888"
    stdin_open: true
    tty: true
    # command: >
    #   sh -c "flutter run -d web-server --web-port=8888 --web-hostname=0.0.0.0"
