version: '3'

services:
  php:
    build: .
    volumes:
      - ./src/:/var/www/html/
      - ./laravel/:/var/www/laravel/
    ports:
      - "8888:80"
      - "8000:8000"
    command: >
      sh -c "
        cd /var/www/laravel/ &&
        php artisan serve --host 0.0.0.0
      "
