version: '3'

services:
  go:
    build: .
    volumes:
      - ./src/:/home/local/src/
    # ports:
    #   - "8888:8888"
    stdin_open: true
    tty: true
    # command: >
    #   sh -c "
    #     go run main.go
    #   "
